import { ReactNode } from "react";
import type { Metadata } from "next";
import "@/assets/styles/globals.css";
import { ThemeProvider } from "./ThemeProvider";

interface ILayout {
  children: ReactNode;
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Layout({ children }: ILayout) {
  return (
    <>
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        {children}
      </ThemeProvider>
    </>
  );
}

export default Layout;
